class Artist < ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[Artist, ActiveRecord_Relation, String]

  attr_accessor id(): String
  def id_changed?: () -> bool
  def id_change: () -> [ String?, String? ]
  def id_will_change!: () -> void
  def id_was: () -> String?
  def id_previously_changed?: () -> bool
  def id_previous_change: () -> Array[String?]?
  def id_previously_was: () -> String?
  def id_before_last_save: () -> String?
  def id_change_to_be_saved: () -> Array[String?]?
  def id_in_database: () -> String?
  def saved_change_to_id: () -> Array[String?]?
  def saved_change_to_id?: () -> bool
  def will_save_change_to_id?: () -> bool
  def restore_id!: () -> void
  def clear_id_change: () -> void

  attr_accessor created_at(): ActiveSupport::TimeWithZone
  def created_at_changed?: () -> bool
  def created_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]
  def created_at_will_change!: () -> void
  def created_at_was: () -> ActiveSupport::TimeWithZone?
  def created_at_previously_changed?: () -> bool
  def created_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?
  def created_at_previously_was: () -> ActiveSupport::TimeWithZone?
  def created_at_before_last_save: () -> ActiveSupport::TimeWithZone?
  def created_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?
  def created_at_in_database: () -> ActiveSupport::TimeWithZone?
  def saved_change_to_created_at: () -> Array[ActiveSupport::TimeWithZone?]?
  def saved_change_to_created_at?: () -> bool
  def will_save_change_to_created_at?: () -> bool
  def restore_created_at!: () -> void
  def clear_created_at_change: () -> void

  attr_accessor updated_at(): ActiveSupport::TimeWithZone
  def updated_at_changed?: () -> bool
  def updated_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]
  def updated_at_will_change!: () -> void
  def updated_at_was: () -> ActiveSupport::TimeWithZone?
  def updated_at_previously_changed?: () -> bool
  def updated_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?
  def updated_at_previously_was: () -> ActiveSupport::TimeWithZone?
  def updated_at_before_last_save: () -> ActiveSupport::TimeWithZone?
  def updated_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?
  def updated_at_in_database: () -> ActiveSupport::TimeWithZone?
  def saved_change_to_updated_at: () -> Array[ActiveSupport::TimeWithZone?]?
  def saved_change_to_updated_at?: () -> bool
  def will_save_change_to_updated_at?: () -> bool
  def restore_updated_at!: () -> void
  def clear_updated_at_change: () -> void

  attr_accessor name(): String
  def name_changed?: () -> bool
  def name_change: () -> [ String?, String? ]
  def name_will_change!: () -> void
  def name_was: () -> String?
  def name_previously_changed?: () -> bool
  def name_previous_change: () -> Array[String?]?
  def name_previously_was: () -> String?
  def name_before_last_save: () -> String?
  def name_change_to_be_saved: () -> Array[String?]?
  def name_in_database: () -> String?
  def saved_change_to_name: () -> Array[String?]?
  def saved_change_to_name?: () -> bool
  def will_save_change_to_name?: () -> bool
  def restore_name!: () -> void
  def clear_name_change: () -> void

  attr_accessor status(): String
  def status_changed?: () -> bool
  def status_change: () -> [ String?, String? ]
  def status_will_change!: () -> void
  def status_was: () -> String?
  def status_previously_changed?: () -> bool
  def status_previous_change: () -> Array[String?]?
  def status_previously_was: () -> String?
  def status_before_last_save: () -> String?
  def status_change_to_be_saved: () -> Array[String?]?
  def status_in_database: () -> String?
  def saved_change_to_status: () -> Array[String?]?
  def saved_change_to_status?: () -> bool
  def will_save_change_to_status?: () -> bool
  def restore_status!: () -> void
  def clear_status_change: () -> void

  attr_accessor pv(): Integer
  def pv_changed?: () -> bool
  def pv_change: () -> [ Integer?, Integer? ]
  def pv_will_change!: () -> void
  def pv_was: () -> Integer?
  def pv_previously_changed?: () -> bool
  def pv_previous_change: () -> Array[Integer?]?
  def pv_previously_was: () -> Integer?
  def pv_before_last_save: () -> Integer?
  def pv_change_to_be_saved: () -> Array[Integer?]?
  def pv_in_database: () -> Integer?
  def saved_change_to_pv: () -> Array[Integer?]?
  def saved_change_to_pv?: () -> bool
  def will_save_change_to_pv?: () -> bool
  def restore_pv!: () -> void
  def clear_pv_change: () -> void

  attr_accessor popularity(): Integer
  def popularity_changed?: () -> bool
  def popularity_change: () -> [ Integer?, Integer? ]
  def popularity_will_change!: () -> void
  def popularity_was: () -> Integer?
  def popularity_previously_changed?: () -> bool
  def popularity_previous_change: () -> Array[Integer?]?
  def popularity_previously_was: () -> Integer?
  def popularity_before_last_save: () -> Integer?
  def popularity_change_to_be_saved: () -> Array[Integer?]?
  def popularity_in_database: () -> Integer?
  def saved_change_to_popularity: () -> Array[Integer?]?
  def saved_change_to_popularity?: () -> bool
  def will_save_change_to_popularity?: () -> bool
  def restore_popularity!: () -> void
  def clear_popularity_change: () -> void

  def artist_has_albums: () -> ArtistHasAlbum::ActiveRecord_Associations_CollectionProxy
  def artist_has_albums=: (ArtistHasAlbum::ActiveRecord_Associations_CollectionProxy | Array[ArtistHasAlbum]) -> (ArtistHasAlbum::ActiveRecord_Associations_CollectionProxy | Array[ArtistHasAlbum])
  def artist_has_album_ids: () -> Array[Integer]
  def artist_has_album_ids=: (Array[Integer]) -> Array[Integer]
  def albums: () -> Album::ActiveRecord_Associations_CollectionProxy
  def albums=: (Album::ActiveRecord_Associations_CollectionProxy | Array[Album]) -> (Album::ActiveRecord_Associations_CollectionProxy | Array[Album])
  def album_ids: () -> Array[Integer]
  def album_ids=: (Array[Integer]) -> Array[Integer]
  def artist_has_tracks: () -> ArtistHasTrack::ActiveRecord_Associations_CollectionProxy
  def artist_has_tracks=: (ArtistHasTrack::ActiveRecord_Associations_CollectionProxy | Array[ArtistHasTrack]) -> (ArtistHasTrack::ActiveRecord_Associations_CollectionProxy | Array[ArtistHasTrack])
  def artist_has_track_ids: () -> Array[Integer]
  def artist_has_track_ids=: (Array[Integer]) -> Array[Integer]
  def tracks: () -> Track::ActiveRecord_Associations_CollectionProxy
  def tracks=: (Track::ActiveRecord_Associations_CollectionProxy | Array[Track]) -> (Track::ActiveRecord_Associations_CollectionProxy | Array[Track])
  def track_ids: () -> Array[Integer]
  def track_ids=: (Array[Integer]) -> Array[Integer]
  def apple_music_artists: () -> AppleMusicArtist::ActiveRecord_Associations_CollectionProxy
  def apple_music_artists=: (AppleMusicArtist::ActiveRecord_Associations_CollectionProxy | Array[AppleMusicArtist]) -> (AppleMusicArtist::ActiveRecord_Associations_CollectionProxy | Array[AppleMusicArtist])
  def apple_music_artist_ids: () -> Array[Integer]
  def apple_music_artist_ids=: (Array[Integer]) -> Array[Integer]
  def favorites: () -> Favorite::ActiveRecord_Associations_CollectionProxy
  def favorites=: (Favorite::ActiveRecord_Associations_CollectionProxy | Array[Favorite]) -> (Favorite::ActiveRecord_Associations_CollectionProxy | Array[Favorite])
  def favorite_ids: () -> Array[Integer]
  def favorite_ids=: (Array[Integer]) -> Array[Integer]

  def pending!: () -> bool
  def pending?: () -> bool
  def active!: () -> bool
  def active?: () -> bool
  def ignore!: () -> bool
  def ignore?: () -> bool
  def self.pending: () -> ActiveRecord_Relation
  def self.active: () -> ActiveRecord_Relation
  def self.ignore: () -> ActiveRecord_Relation
  def self.include_album_services: () -> ActiveRecord_Relation
  def self.include_albums: () -> ActiveRecord_Relation
  def self.include_tracks: () -> ActiveRecord_Relation
  def self.include_services: () -> ActiveRecord_Relation
  def self.services: () -> ActiveRecord_Relation
  def self.names: () -> ActiveRecord_Relation

  module GeneratedRelationMethods
    def pending: () -> ActiveRecord_Relation

    def active: () -> ActiveRecord_Relation

    def ignore: () -> ActiveRecord_Relation

    def include_album_services: () -> ActiveRecord_Relation

    def include_albums: () -> ActiveRecord_Relation

    def include_tracks: () -> ActiveRecord_Relation

    def include_services: () -> ActiveRecord_Relation

    def services: () -> ActiveRecord_Relation

    def names: () -> ActiveRecord_Relation
  end

  class ActiveRecord_Relation < ActiveRecord::Relation
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[Artist, String]
    include Enumerable[Artist]
  end

  class ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[Artist, String]
  end
end
