class PublicInformation < ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[PublicInformation, ActiveRecord_Relation, String]

  attr_accessor id(): String
  def id_changed?: () -> bool
  def id_change: () -> [ String?, String? ]
  def id_will_change!: () -> void
  def id_was: () -> String?
  def id_previously_changed?: () -> bool
  def id_previous_change: () -> Array[String?]?
  def id_previously_was: () -> String?
  def id_before_last_save: () -> String?
  def id_change_to_be_saved: () -> Array[String?]?
  def id_in_database: () -> String?
  def saved_change_to_id: () -> Array[String?]?
  def saved_change_to_id?: () -> bool
  def will_save_change_to_id?: () -> bool
  def restore_id!: () -> void
  def clear_id_change: () -> void

  attr_accessor created_at(): ActiveSupport::TimeWithZone
  def created_at_changed?: () -> bool
  def created_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]
  def created_at_will_change!: () -> void
  def created_at_was: () -> ActiveSupport::TimeWithZone?
  def created_at_previously_changed?: () -> bool
  def created_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?
  def created_at_previously_was: () -> ActiveSupport::TimeWithZone?
  def created_at_before_last_save: () -> ActiveSupport::TimeWithZone?
  def created_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?
  def created_at_in_database: () -> ActiveSupport::TimeWithZone?
  def saved_change_to_created_at: () -> Array[ActiveSupport::TimeWithZone?]?
  def saved_change_to_created_at?: () -> bool
  def will_save_change_to_created_at?: () -> bool
  def restore_created_at!: () -> void
  def clear_created_at_change: () -> void

  attr_accessor updated_at(): ActiveSupport::TimeWithZone
  def updated_at_changed?: () -> bool
  def updated_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]
  def updated_at_will_change!: () -> void
  def updated_at_was: () -> ActiveSupport::TimeWithZone?
  def updated_at_previously_changed?: () -> bool
  def updated_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?
  def updated_at_previously_was: () -> ActiveSupport::TimeWithZone?
  def updated_at_before_last_save: () -> ActiveSupport::TimeWithZone?
  def updated_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?
  def updated_at_in_database: () -> ActiveSupport::TimeWithZone?
  def saved_change_to_updated_at: () -> Array[ActiveSupport::TimeWithZone?]?
  def saved_change_to_updated_at?: () -> bool
  def will_save_change_to_updated_at?: () -> bool
  def restore_updated_at!: () -> void
  def clear_updated_at_change: () -> void

  attr_accessor user_id(): String
  def user_id_changed?: () -> bool
  def user_id_change: () -> [ String?, String? ]
  def user_id_will_change!: () -> void
  def user_id_was: () -> String?
  def user_id_previously_changed?: () -> bool
  def user_id_previous_change: () -> Array[String?]?
  def user_id_previously_was: () -> String?
  def user_id_before_last_save: () -> String?
  def user_id_change_to_be_saved: () -> Array[String?]?
  def user_id_in_database: () -> String?
  def saved_change_to_user_id: () -> Array[String?]?
  def saved_change_to_user_id?: () -> bool
  def will_save_change_to_user_id?: () -> bool
  def restore_user_id!: () -> void
  def clear_user_id_change: () -> void

  attr_accessor public_type(): String
  def public_type_changed?: () -> bool
  def public_type_change: () -> [ String?, String? ]
  def public_type_will_change!: () -> void
  def public_type_was: () -> String?
  def public_type_previously_changed?: () -> bool
  def public_type_previous_change: () -> Array[String?]?
  def public_type_previously_was: () -> String?
  def public_type_before_last_save: () -> String?
  def public_type_change_to_be_saved: () -> Array[String?]?
  def public_type_in_database: () -> String?
  def saved_change_to_public_type: () -> Array[String?]?
  def saved_change_to_public_type?: () -> bool
  def will_save_change_to_public_type?: () -> bool
  def restore_public_type!: () -> void
  def clear_public_type_change: () -> void

  def user: () -> User
  def user=: (User?) -> User?
  def reload_user: () -> User?
  def build_user: (untyped) -> User
  def create_user: (untyped) -> User
  def create_user!: (untyped) -> User

  def artist!: () -> bool
  def artist?: () -> bool
  def album!: () -> bool
  def album?: () -> bool
  def track!: () -> bool
  def track?: () -> bool
  def playlist!: () -> bool
  def playlist?: () -> bool
  def self.artist: () -> ActiveRecord_Relation
  def self.album: () -> ActiveRecord_Relation
  def self.track: () -> ActiveRecord_Relation
  def self.playlist: () -> ActiveRecord_Relation

  module GeneratedRelationMethods
    def artist: () -> ActiveRecord_Relation

    def album: () -> ActiveRecord_Relation

    def track: () -> ActiveRecord_Relation

    def playlist: () -> ActiveRecord_Relation
  end

  class ActiveRecord_Relation < ActiveRecord::Relation
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[PublicInformation, String]
    include Enumerable[PublicInformation]
  end

  class ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[PublicInformation, String]
  end
end
