module Html
  class Ogp
    def self.convert: (::String path) -> ::String
    def self.add_env: (untyped header) -> untyped
    def self.build_metatag: (
      untyped header,
      ::String content,
      **untyped
    ) -> untyped
  end
end
