module JWT
  def self.encode: (
    *untyped,
    **untyped
  ) ?{
    (*untyped, **untyped) -> untyped
  } -> ::String

  def self.decode: (
    *untyped,
    **untyped
  ) ?{
    (*untyped, **untyped) -> untyped
  } -> ::Array[::String]
end
