module Types
  module InputObjects
    class BaseInputObject < ::GraphQL::Schema::InputObject
      def self.arguments: -> ::Hash[untyped, untyped]
      def self.default_argument_values: -> ::Hash[::Symbol, untyped]
    end
  end
end
