AllCops:
  NewCops: enable
  EnabledByDefault: true
  Exclude:
    - "vendor/**/*"
    - "bin/**/*"
    - "db/schema.rb"

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/NumberConversion:
  IgnoredMethods:
    - from_now

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/PredicateName:
  Exclude:
    - app/graphql/**/*.rb

Style/AsciiComments:
  Enabled: false

Style/ClassMethodsDefinitions:
  Enabled: true
  EnforcedStyle: self_class

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/StaticClass:
  Enabled: false

Style/SymbolProc:
  Enabled: false
