AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  EnabledByDefault: true
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"

Style/Copyright:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/NumberConversion:
  Enabled: false
