class Album < ::ApplicationRecord
  def self.find_by_isrc: (::Array[::String] isrc) -> ::Album?
  def self.all_pending_to_ignore: -> untyped
  def self.statuses: -> ::Hash[::String, ::Integer]
  def self.cache?: (conditions: ::Query::conditions) -> bool
  def self.generate_relation: (
    conditions: ::Query::conditions,
    context: ::GraphQL::Query::context
  ) -> untyped
  def self.create_by_new_releases: -> untyped
  def sync_tracks_status: -> untyped
  def force_ignore: -> untyped
  def update_services: -> ::Album
  def to_url: -> ::String
  def service: -> ::AppleMusicAlbum?
  def tracks_composers: -> ::Array[::Artist]
  def composers: -> ::Array[::Artist]
end
