class AlbumHasTrack < ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[AlbumHasTrack, AlbumHasTrack::ActiveRecord_Relation]

  attr_accessor id (): String
  def id_changed?: () -> bool
  def id_change: () -> [String?, String?]
  def id_will_change!: () -> void
  def id_was: () -> String?
  def id_previously_changed?: () -> bool
  def id_previous_change: () -> Array[String?]?
  def id_previously_was: () -> String?
  def restore_id!: () -> void
  def clear_id_change: () -> void

  attr_accessor created_at (): Time
  def created_at_changed?: () -> bool
  def created_at_change: () -> [Time?, Time?]
  def created_at_will_change!: () -> void
  def created_at_was: () -> Time?
  def created_at_previously_changed?: () -> bool
  def created_at_previous_change: () -> Array[Time?]?
  def created_at_previously_was: () -> Time?
  def restore_created_at!: () -> void
  def clear_created_at_change: () -> void

  attr_accessor updated_at (): Time
  def updated_at_changed?: () -> bool
  def updated_at_change: () -> [Time?, Time?]
  def updated_at_will_change!: () -> void
  def updated_at_was: () -> Time?
  def updated_at_previously_changed?: () -> bool
  def updated_at_previous_change: () -> Array[Time?]?
  def updated_at_previously_was: () -> Time?
  def restore_updated_at!: () -> void
  def clear_updated_at_change: () -> void

  attr_accessor album_id (): String
  def album_id_changed?: () -> bool
  def album_id_change: () -> [String?, String?]
  def album_id_will_change!: () -> void
  def album_id_was: () -> String?
  def album_id_previously_changed?: () -> bool
  def album_id_previous_change: () -> Array[String?]?
  def album_id_previously_was: () -> String?
  def restore_album_id!: () -> void
  def clear_album_id_change: () -> void

  attr_accessor track_id (): String
  def track_id_changed?: () -> bool
  def track_id_change: () -> [String?, String?]
  def track_id_will_change!: () -> void
  def track_id_was: () -> String?
  def track_id_previously_changed?: () -> bool
  def track_id_previous_change: () -> Array[String?]?
  def track_id_previously_was: () -> String?
  def restore_track_id!: () -> void
  def clear_track_id_change: () -> void



  def album: () -> Album
  def track: () -> Track



end

class AlbumHasTrack::ActiveRecord_Relation < ActiveRecord::Relation
  include _ActiveRecord_Relation[AlbumHasTrack]
  include Enumerable[AlbumHasTrack, self]


end

class AlbumHasTrack::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
