class AllowedAction < ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[AllowedAction, AllowedAction::ActiveRecord_Relation]

  attr_accessor id (): String
  def id_changed?: () -> bool
  def id_change: () -> [String?, String?]
  def id_will_change!: () -> void
  def id_was: () -> String?
  def id_previously_changed?: () -> bool
  def id_previous_change: () -> Array[String?]?
  def id_previously_was: () -> String?
  def restore_id!: () -> void
  def clear_id_change: () -> void

  attr_accessor created_at (): Time
  def created_at_changed?: () -> bool
  def created_at_change: () -> [Time?, Time?]
  def created_at_will_change!: () -> void
  def created_at_was: () -> Time?
  def created_at_previously_changed?: () -> bool
  def created_at_previous_change: () -> Array[Time?]?
  def created_at_previously_was: () -> Time?
  def restore_created_at!: () -> void
  def clear_created_at_change: () -> void

  attr_accessor updated_at (): Time
  def updated_at_changed?: () -> bool
  def updated_at_change: () -> [Time?, Time?]
  def updated_at_will_change!: () -> void
  def updated_at_was: () -> Time?
  def updated_at_previously_changed?: () -> bool
  def updated_at_previous_change: () -> Array[Time?]?
  def updated_at_previously_was: () -> Time?
  def restore_updated_at!: () -> void
  def clear_updated_at_change: () -> void

  attr_accessor role_id (): String
  def role_id_changed?: () -> bool
  def role_id_change: () -> [String?, String?]
  def role_id_will_change!: () -> void
  def role_id_was: () -> String?
  def role_id_previously_changed?: () -> bool
  def role_id_previous_change: () -> Array[String?]?
  def role_id_previously_was: () -> String?
  def restore_role_id!: () -> void
  def clear_role_id_change: () -> void

  attr_accessor name (): String
  def name_changed?: () -> bool
  def name_change: () -> [String?, String?]
  def name_will_change!: () -> void
  def name_was: () -> String?
  def name_previously_changed?: () -> bool
  def name_previous_change: () -> Array[String?]?
  def name_previously_was: () -> String?
  def restore_name!: () -> void
  def clear_name_change: () -> void



  def role: () -> Role

  # rbs prototype rb app/models/allowed_action.rb
  MUTATION_ACTIONS: Array[String]

  QUERY_ACTIONS: Array[String]

  CONSOLE_ACTIONS: Array[String]

  DEFAULT_ACTIONS: Array[String]

  ALL_ACTIONS: Array[String]
end

class AllowedAction::ActiveRecord_Relation < ActiveRecord::Relation
  include _ActiveRecord_Relation[AllowedAction]
  include Enumerable[AllowedAction, self]


end

class AllowedAction::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
