class AppleMusicAlbum < ApplicationRecord
  include MusicServiceCreatable

  include Albums::Compact

  def self.music_service_id_name: () -> "apple_music_id"

  def self.mapping: (untyped data) -> untyped

  def self.to_album_attrs: (untyped data) -> { release_date: untyped, total_tracks: untyped }

  def self.create_by_music_service_id: (untyped apple_music_id) -> (nil | untyped)

  # トラックのISRC1件でアルバム特定し生成する
  def self.create_by_track_isrc: (untyped isrc) -> (::Array[untyped] | untyped)

  def self.new_releases_apple_music_ids: (?::Integer genre) -> untyped

  def self.create_by_new_releases: (?::Integer genre) -> (::Array[untyped] | untyped)

  def music_service_id: () -> untyped

  def artwork_l: () -> untyped

  def artwork_m: () -> untyped

  private

  def build_artwork: (untyped max_size) -> untyped

  public

  def sync_status_apple_music_tracks: () -> untyped
end
