class AppleMusicTrack < ApplicationRecord
  include Searchable

  def self.mapping: (untyped data) -> untyped

  def self.to_track_attrs: (untyped data) -> { isrc: untyped }

  def music_service_id: () -> untyped

  def artwork_l: () -> untyped

  def artwork_m: () -> untyped

  private

  def build_artwork: (untyped max_size) -> untyped
end
