class ApplicationRecord < ::ActiveRecord::Base
  include ::TTID::InstanceMethods

  def self.find_or_initialize_by: (
    *untyped,
    **untyped
  ) ?{
    (instance, **untyped) -> untyped
  } -> instance

  def self.find_or_create_by: (
    *untyped,
    **untyped
  ) ?{
    (instance, **untyped) -> untyped
  } -> instance
end
