class AppleMusicArtist < ApplicationRecord
  include MusicServiceCreatable

  def self.music_service_id_name: () -> "apple_music_id"

  def self.mapping: (untyped data) -> { artist_id: untyped, apple_music_id: untyped, name: untyped, status: untyped }

  def self.create_by_name: (untyped name) -> untyped

  def self.create_by_music_service_id: (untyped apple_music_id) -> (nil | untyped)

  def music_service_id: () -> untyped

  def create_albums: () -> (::Array[untyped] | untyped)

  def artwork_l: () -> untyped

  def artwork_m: () -> untyped
end
