class Artist
  def self.all_pending_to_ignore: -> untyped
  def self.cache?: (conditions: ::Query::conditions) -> bool
  def self.generate_relation: (
    conditions: ::Query::conditions,
    context: ::GraphQL::Query::context
  ) -> untyped
  def artwork_l: -> ::Artwork
  def artwork_m: -> ::Artwork
  def service_album: -> ::AppleMusicAlbum?
end
