class Artist < ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[Artist, Artist::ActiveRecord_Relation]

  attr_accessor id (): String
  attr_accessor created_at (): Time
  attr_accessor updated_at (): Time
  attr_accessor name (): String
  attr_accessor status (): String # enum なので Integer ではなく String
  def artist_has_albums: () -> ArtistHasAlbum::ActiveRecord_Associations_CollectionProxy
  def albums: () -> Album::ActiveRecord_Associations_CollectionProxy
  def artist_has_tracks: () -> ArtistHasTrack::ActiveRecord_Associations_CollectionProxy
  def tracks: () -> Track::ActiveRecord_Associations_CollectionProxy
  def apple_music_artists: () -> AppleMusicArtist::ActiveRecord_Associations_CollectionProxy
  def spotify_artists: () -> SpotifyArtist::ActiveRecord_Associations_CollectionProxy
  def favorites: () -> Favorite::ActiveRecord_Associations_CollectionProxy


  def pending!: () -> bool
  def pending?: () -> bool
  def active!: () -> bool
  def active?: () -> bool
  def ignore!: () -> bool
  def ignore?: () -> bool
  def self.pending: () -> Artist::ActiveRecord_Relation
  def self.active: () -> Artist::ActiveRecord_Relation
  def self.ignore: () -> Artist::ActiveRecord_Relation
  def self.include_albums: () -> Artist::ActiveRecord_Relation
  def self.include_services: () -> Artist::ActiveRecord_Relation
  def self.services: () -> Artist::ActiveRecord_Relation
  def self.names: () -> Artist::ActiveRecord_Relation

  # rbs prototype rb app/models/artist.rb
  include Artists::Status

  include Artists::Mix

  FORCE_IGNORE_NAMES: ::Array[untyped]

  def self.create_by_name: (String name) -> Artist::ActiveRecord_Relation

  def self.to_name: (String name) -> String

  def self.all_pending_to_ignore: () -> Array[instance]

  def self.all_create_albums: () -> Array[instance]

  def create_albums: () -> self

  def service: () -> (SpotifyArtist | AppleMusicArtist | nil)

  def to_path: () -> ::String

  def to_url: () -> ::String
end

class Artist::ActiveRecord_Relation < ::ActiveRecord::Relation
  include _ActiveRecord_Relation[Artist]
  include Enumerable[Artist, self]
  def pending: () -> Artist::ActiveRecord_Relation
  def active: () -> Artist::ActiveRecord_Relation
  def ignore: () -> Artist::ActiveRecord_Relation
  def include_albums: () -> Artist::ActiveRecord_Relation
  def include_services: () -> Artist::ActiveRecord_Relation
  def services: () -> Artist::ActiveRecord_Relation
  def names: () -> Artist::ActiveRecord_Relation
end

class Artist::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
  include Artist::ActiveRecord_Relation
end
