class Artwork < ::ApplicationRecord
  include ::ActiveModel::Model
  include ::ActiveModel::Attributes
  extend ::ActiveModel::Attributes::ClassMethods
  def url: -> ::String
  def width: -> ::Integer
  def height: -> ::Integer
end
