class IgnoreContent < ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[IgnoreContent, IgnoreContent::ActiveRecord_Relation]

  attr_accessor id (): String
  def id_changed?: () -> bool
  def id_change: () -> [String?, String?]
  def id_will_change!: () -> void
  def id_was: () -> String?
  def id_previously_changed?: () -> bool
  def id_previous_change: () -> Array[String?]?
  def id_previously_was: () -> String?
  def restore_id!: () -> void
  def clear_id_change: () -> void

  attr_accessor created_at (): Time
  def created_at_changed?: () -> bool
  def created_at_change: () -> [Time?, Time?]
  def created_at_will_change!: () -> void
  def created_at_was: () -> Time?
  def created_at_previously_changed?: () -> bool
  def created_at_previous_change: () -> Array[Time?]?
  def created_at_previously_was: () -> Time?
  def restore_created_at!: () -> void
  def clear_created_at_change: () -> void

  attr_accessor updated_at (): Time
  def updated_at_changed?: () -> bool
  def updated_at_change: () -> [Time?, Time?]
  def updated_at_will_change!: () -> void
  def updated_at_was: () -> Time?
  def updated_at_previously_changed?: () -> bool
  def updated_at_previous_change: () -> Array[Time?]?
  def updated_at_previously_was: () -> Time?
  def restore_updated_at!: () -> void
  def clear_updated_at_change: () -> void

  attr_accessor music_service_id (): String
  def music_service_id_changed?: () -> bool
  def music_service_id_change: () -> [String?, String?]
  def music_service_id_will_change!: () -> void
  def music_service_id_was: () -> String?
  def music_service_id_previously_changed?: () -> bool
  def music_service_id_previous_change: () -> Array[String?]?
  def music_service_id_previously_was: () -> String?
  def restore_music_service_id!: () -> void
  def clear_music_service_id_change: () -> void

  attr_accessor title (): String
  def title_changed?: () -> bool
  def title_change: () -> [String?, String?]
  def title_will_change!: () -> void
  def title_was: () -> String?
  def title_previously_changed?: () -> bool
  def title_previous_change: () -> Array[String?]?
  def title_previously_was: () -> String?
  def restore_title!: () -> void
  def clear_title_change: () -> void

  attr_accessor reason (): String
  def reason_changed?: () -> bool
  def reason_change: () -> [String?, String?]
  def reason_will_change!: () -> void
  def reason_was: () -> String?
  def reason_previously_changed?: () -> bool
  def reason_previous_change: () -> Array[String?]?
  def reason_previously_was: () -> String?
  def restore_reason!: () -> void
  def clear_reason_change: () -> void







end

class IgnoreContent::ActiveRecord_Relation < ActiveRecord::Relation
  include _ActiveRecord_Relation[IgnoreContent]
  include Enumerable[IgnoreContent, self]


end

class IgnoreContent::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
