class PlaylistCondition < ::ActiveRecord::Base
  type conditions =
    {
      order: ['popularity', 'release_date', 'created_at'],
      asc: bool,
      favorite: bool,
      min_popularity: ::Integer,
      max_popularity: ::Integer,
      from_release_date: ::String,
      to_release_date: ::String
    }
end
