class PlaylistCondition < ::ActiveRecord::Base
  type conditions =
    {
      order: ::String,
      direction: ::String,
      favorite: bool,
      min_popularity: ::Integer,
      max_popularity: ::Integer,
      from_release_date: ::String,
      to_release_date: ::String
    }
end
