class Session < ::ApplicationRecord
  EXPIRE_DAYS: ::ActiveSupport::Duration

  def refresh_token: -> ::String
  def digit_token: -> ::String

  def self.find_by_digit_token!: (::String digit_token) -> ::Session
end
