class Track
  def self.cache?: (conditions: ::Query::conditions) -> bool
  def self.generate_relation: (
    conditions: ::Query::conditions,
    context: ::GraphQL::Query::context
  ) -> untyped
  def service: -> ::AppleMusicTrack?
end
