class Track < ApplicationRecord
  def service: () -> untyped

  def apple_music_tracks: () -> untyped

  def itunes_tracks: () -> untyped

  def pick_apple_track: (untyped is_apple_music) -> (::Array[untyped] | untyped)
end
