class User < ::ApplicationRecord
  def self.create_user_and_session!: -> ::User
  def can?: (::String action_name) -> bool
  def authenticate: (*untyped) -> bool
  def create_session: -> ::Session
end
