class ApplicationRecord < ActiveRecord::Base
end
class ArtistHasAlbum::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Artist::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class AlbumHasTrack::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Track::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Favorite::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class AppleMusicTrack::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class AppleMusicTrackWord::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Album::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class ArtistHasTrack::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class AppleMusicArtist::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class PlaylistItem::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class PlaylistCondition::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class User::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class AllowedAction::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Session::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class ActiveRecord::Associations::CollectionProxy < ActiveRecord::Relation
end
class ActiveRecord::Relation < Object
end
module ActiveRecord::Associations
end
