# TTID
# Table id, hex Timestamp, ID
module TTID : ApplicationRecord
  extend ActiveSupport::Concern

  REGEXP: ::Regexp

  def self.to_hash: (String id) -> (nil | { table_id: String, hex_timestamp: String, hex_id: String })

  def self.decode: (String id) -> (nil | { model: ApplicationRecord, timestamp: Time, hex_id: String })

  def self.to_timestamp: (String hex_timestamp) -> Time

  def self.table_info: () -> Hash[String, ApplicationRecord]

  def self.add_table_info: (Hash[String, ApplicationRecord] info) -> Hash[String, ApplicationRecord]

  def self.unix_timestamp_usec3: () -> Integer

  def identify: () -> String

  def build_id: () -> String

  module ClassMethods : ApplicationRecord
    # 検証元のクラスと検証したいID
    def validate_ids!: (Array[String] ids) -> ::TrueClass

    def table_id: (?Symbol _table_id) -> String

    def hex_time: () -> String

    def build_id: () -> String
  end
end
