class Monitor
end
class MonitorMixin
end

module Singleton
end

module PG
end

module Nokogiri
  module HTML
    def self.parse: (String) -> Nokogiri::HTML::Document

    class Document
      def at: (String) -> Nokogiri::XML::Element
      def to_s: () -> String
    end
  end

  module XML
    class Element
      def <<: (Nokogiri::XML::Node) -> Nokogiri::XML::Element
    end

    class Node
      def initialize: (*untyped) -> untyped
      def []=: (untyped key, untyped value) -> untyped
    end
  end
end
