module Types
  module Enums
    class EnumDummy
      def value: -> ::String
    end
    class BaseEnum < ::GraphQL::Schema::Enum
      def self.values: -> ::Hash[::String, untyped]
    end
  end
end
