# ユーザーお気に入り関連
module Users
  module Favorite
    extend ActiveSupport::Concern

    class UserFavorite
      attr_reader user_id: untyped

      def initialize: (untyped user_id) -> void

      def artist_ids: () -> untyped

      def album_ids: () -> untyped

      def track_ids: () -> untyped

      def playlist_ids: () -> untyped

      def radio_ids: () -> untyped
    end

    def favorite: () -> untyped
  end
end
