module Queries
  class Albums < BaseListQuery
    class AlbumsQueryOrderEnum < Types::Enums::BaseEnum
    end

    class AlbumsSortInputObject < Types::InputObjects::BaseInputObject
    end

    class AlbumsConditionsInputObject < Types::InputObjects::BaseInputObject
    end

    def list_query: (cursor: untyped cursor, sort: untyped sort, ?conditions: ::Hash[untyped, untyped] conditions) -> ::Array[untyped]

    # 汚すぎてどうしようか
    def self.build_relation: (context: untyped context, ?conditions: ::Hash[untyped, untyped] conditions) -> ::Array[untyped]
  end
end
