module Queries
  class ArtistsQuery < ::Queries::BaseListQuery
    class ArtistsQueryOrderEnum < ::Types::Enums::BaseEnum
    end

    class ArtistsSortInputObject < ::Types::InputObjects::BaseInputObject
    end

    class ArtistsConditionsInputObject < ::Types::InputObjects::BaseInputObject
    end
  end
end
