module Queries
  class BaseQuery < GraphQL::Schema::Resolver
    include Types::Scalars

    include Types::Objects

    include Types::InputObjects

    include Types::Enums

    def resolve: (**untyped args) -> untyped
  end
end
