module Queries
  class Playlists < BaseListQuery
    class PlaylistsQueryOrderEnum < Types::Enums::BaseEnum
    end

    class PlaylistsSortInputObject < Types::InputObjects::BaseInputObject
    end

    class PlaylistsConditionsInputObject < Types::InputObjects::BaseInputObject
    end

    # キャッシュしない
    def list_query: (cursor: untyped cursor, sort: untyped sort, ?conditions: ::Hash[untyped, untyped] conditions) -> ::Array[untyped]
  end
end
