module Queries
  class Radios < BaseListQuery
    class RadiosQueryOrderEnum < Types::Enums::BaseEnum
    end

    class RadiosSortInputObject < Types::InputObjects::BaseInputObject
    end

    class RadiosConditionsInputObject < Types::InputObjects::BaseInputObject
    end

    def list_query: (cursor: untyped cursor, sort: untyped sort, ?conditions: ::Hash[untyped, untyped] conditions) -> ::Array[untyped]
  end
end
