module Queries
  class Tracks < BaseListQuery
    class TracksQueryOrderEnum < Types::Enums::BaseEnum
    end

    class TracksSortInputObject < Types::InputObjects::BaseInputObject
    end

    class TracksConditionsInputObject < Types::InputObjects::BaseInputObject
    end

    def list_query: (cursor: untyped cursor, sort: untyped sort, ?conditions: ::Hash[untyped, untyped] conditions) -> ::Array[untyped]
  end
end
