class ApplicationController < ::ActionController::Base
  type current_info =
    { user: ::User, session: ::Session | nil, cookie: untyped }

  @current_info: current_info

  def current_info: -> current_info
  def refresh_token: -> untyped
  def platform: -> ('ios' | 'web')
  def web?: -> bool

  private

  def token: -> ::String
  def create_current_info: -> current_info
end
