class GraphqlController < ::ApplicationController
  def execute: -> untyped

  private

  def token!: (::Hash[untyped, untyped] result) -> untyped

  def ensure_hash: (untyped ambiguous_param) -> untyped

  def handle_error_in_development: (::StandardError e) -> untyped
end
