default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['SERVER_DATABASE_HOST'] %>
  username: <%= ENV['SERVER_DATABASE_USER_NAME_DEVELOP'] %>
  password: <%= ENV['SERVER_DATABASE_USER_PASSWORD_DEVELOP'] %>

development:
  <<: *default
  database: <%= ENV['SERVER_DATABASE_NAME_DEVELOP'] %>

test:
  <<: *default
  database: <%= ENV['SERVER_DATABASE_NAME_TEST'] %>

production:
  <<: *default
  database: <%= ENV['SERVER_DATABASE_NAME_PRODUCTION'] %>
  username: <%= ENV['SERVER_DATABASE_USER_NAME_PRODUCTION'] %>
  password: <%= ENV['SERVER_DATABASE_USER_PASSWORD_PRODUCTION'] %>
