class Faraday
  def self.default_adapter: (*untyped, **untyped) ?{ (*untyped, **untyped) -> untyped } -> untyped
  def self.post: (String) ?{ (::Faraday::Connection) -> ::Faraday::Response } -> ::Faraday::Response

  def initialize: (*untyped, **untyped) ?{ (::Faraday::Connection) -> ::Faraday::Connection } -> ::Faraday::Connection

  class Connection
    def initialize: (*untyped, **untyped) ?{ (instance) -> instance } -> instance
    def use: (*untyped) ?{ (untyped) -> untyped } -> untyped
    def headers: (*untyped) ?{ (untyped) -> untyped } -> untyped
    def authorization: (*untyped) ?{ (untyped) -> untyped } -> untyped
    def adapter: (*untyped) ?{ (untyped) -> untyped } -> untyped
    def body=: (*untyped) ?{ (untyped) -> untyped } -> untyped
  end

  class Response
    def body: () -> String
  end
end
