module DRb
end

module DRb::DRbUndumped
end

module TSort
end

class SimpleDelegator
end

module Gem
  class Version
  end
end

module OpenSSL
  class Cipher
  end

  class PKey
    class EC
      def initialize:(String) -> untyped

      def check_key: () -> untyped
    end
  end
end

module FileUtils
end
