module AppleMusic
  class Api
    ENDPOINT: ::String

    RSS_ENDPOINT: ::String

    LOCALE: ::String

    DEFAULT_REPEAT: ::Integer

    ALL_GENRES: ::Hash[::Symbol, ::String]

    def self.apple_music_most_played: -> ResponseFeed::feed_attributes

    @client: ::AppleMusic::Client

    @locale: ::String

    @repeat: ::Integer

    def get: (::String url, ?::Hash[::String, untyped]? params) -> untyped

    def get_artist: (::String apple_music_id) -> Response::artists

    def get_artist_albums: (
      ::String apple_music_id,
      ?::Integer repeat
    ) -> Response::albums

    def get_artist_tracks: (
      ::String apple_music_id,
      ?::Integer repeat
    ) -> Response::tracks

    def get_album: (::String apple_music_id) -> Response::albums

    def get_track: (::String apple_music_id) -> Response::tracks

    def get_track_by_isrc: (::String isrc) -> Response::tracks

    def get_chart_albums: (
      ::Integer genre,
      ::Integer limit
    ) -> ResponseChart::chart_albums

    def get_chart_tracks: (
      ::Integer genre,
      ::Integer limit
    ) -> ResponseChart::chart_tracks

    private

    def compound: (::Hash[::String, untyped] body) -> untyped

    def catalog_url: -> ::String

    module Response
      type artist_attributes =
        {
          "name" => ::String,
          "genreNames" => ::Array[::String],
          "url" => ::String
        }

      type artwork_attributes =
        {
          "width" => ::Integer,
          "height" => ::Integer,
          "url" => ::String,
          "bgColor" => ::String,
          "textColor1" => ::String,
          "textColor2" => ::String,
          "textColor3" => ::String,
          "textColor4" => ::String
        }

      type album_attributes =
        {
          "artwork" => artwork_attributes,
          "artistName" => ::String,
          "isSingle" => bool,
          "url" => ::String,
          "isComplete" => bool,
          "genreNames" => ::Array[::String],
          "trackCount" => ::Integer,
          "isMasteredForItunes" => bool,
          "releaseDate" => ::String,
          "name" => ::String,
          "recordLabel" => ::String,
          "upc" => ::String,
          "copyright" => ::String,
          "playParams" => { "id" => ::String, "kind" => 'album' } | nil,
          "isCompilation" => bool
        }

      type track_attributes =
        {
          "previews" => ::Array[{ "url" => ::String }],
          "artwork" => artwork_attributes,
          "artistName" => ::String,
          "url" => ::String,
          "discNumber" => ::Integer,
          "genreNames" => ::Array[::String],
          "durationInMillis" => ::Integer,
          "releaseDate" => ::String,
          "name" => ::String,
          "isrc" => ::String,
          "hasLyrics" => bool,
          "albumName" => ::String,
          "playParams" => { "id" => ::String, "kind" => 'song' } | nil,
          "trackNumber" => ::Integer,
          "composerName" => ::String | nil
        }

      type simple_artist =
        {
          "id" => ::String,
          "type" => 'artists',
          "href" => ::String,
          "attributes" => artist_attributes
        }

      type artist =
        {
          "id" => ::String,
          "type" => 'artists',
          "href" => ::String,
          "attributes" => artist_attributes?,
          "relationships" => {
            "albums" => {
              "next" => ::String | nil,
              "href" => ::String,
              "data" => ::Array[simple_album]
            }
          }
        }

      type artists = { "next" => ::String | nil, "data" => Array[artist] }

      type simple_album =
        {
          "id" => ::String,
          "type" => 'albums',
          "href" => ::String,
          "attributes" => album_attributes
        }

      type album =
        {
          "id" => ::String,
          "type" => 'albums',
          "href" => ::String,
          "attributes" => album_attributes,
          "relationships" => {
            "tracks" => {
              "next" => ::String | nil,
              "href" => ::String,
              "data" => ::Array[simple_track]
            },
            "artists" => {
              "next" => ::String | nil,
              "href" => ::String,
              "data" => ::Array[simple_artist]
            }
          }
        }

      type albums = { "next" => ::String | nil, "data" => Array[album] }

      type simple_track =
        {
          "id" => ::String,
          "type" => 'songs' | 'music-videos',
          "href" => ::String,
          "attributes" => track_attributes
        }

      type track =
        {
          "id" => ::String,
          "type" => 'songs' | 'music-videos',
          "href" => ::String,
          "attributes" => track_attributes,
          "relationships" => {
            "artists" => {
              "next" => ::String | nil,
              "href" => ::String,
              "data" => ::Array[simple_artist]
            },
            "albums" => {
              "next" => ::String | nil,
              "href" => ::String,
              "data" => ::Array[simple_album]
            }
          }
        }

      type tracks = { "next" => ::String | nil, "data" => Array[track] }

      type index_results =
        {
          "results" => { "artists" => artists },
          "meta" => {
            "results" => { "order" => ['artists'], "rawOrder" => ['artists'] }
          }
        }
    end

    module ResponseChart
      type chart_albums =
        {
          "results" => {
            "albums" => {
              "chart" => 'most-played',
              "name" => 'トップアルバム',
              "orderId" => 'most-played:albums',
              "next" => ::String,
              "data" => ::Array[Response::simple_album]
            },
            "href" => ::String
          },
          "meta" => { "results" => { "order" => ::Array[::String] } }
        }

      type chart_tracks =
        {
          "results" => {
            "songs" => {
              "chart" => 'most-played',
              "name" => 'トップソング',
              "orderId" => 'most-played:songs',
              "next" => ::String,
              "data" => ::Array[Response::simple_track]
            },
            "href" => ::String
          },
          "meta" => { "results" => { "order" => ::Array[::String] } }
        }
    end

    module ResponseFeed
      type feed_attributes =
        {
          "feed" => {
            "title" => ::String,
            "id" => ::String,
            "author" => {
              "name" => 'Apple',
              "url" => 'https://www.apple.com/'
            },
            "links" => ::Array[{ "self" => ::String }],
            "copyright" => 'Copyright © 2021 Apple Inc. All rights reserved.',
            "country" => ::String,
            "icon" => 'https://www.apple.com/favicon.ico',
            "updated" => ::String,
            "results" => ::Array[{
              "artistName" => ::String,
              "id" => ::String,
              "name" => ::String,
              "releaseDate" => ::String,
              "kind" => 'album',
              "artistId" => ::String,
              "artistUrl" => ::String,
              "artworkUrl100" => ::String,
              "url" => ::String,
              "genres" => ::Array[{
                "genreId" => ::String,
                "name" => ::String,
                "url" => ::String
              }]
            }]
          }
        }
    end
  end
end
