module AppleMusic
  class Token
    type token = {
      access_token: String,
      token_type: "Bearer",
      expires_on: Time
    }

    def self.create_client_token: () -> token

    def self.create_server_token: () -> token

    def self.create: (String private_key, String keyId, Integer hours) -> token
  end
end
