module Ggl
  class Analytics
    def self.analytics: -> ::Google::Apis::AnalyticsreportingV4
    def self.valid?: (::String token) -> bool
    def self.request: (::String token) -> { "success" => bool }
    def self.json_file: -> untyped
    def self.client: -> ::Google::Apis::AnalyticsreportingV4::AnalyticsReportingService
    def self.pv_report: (
      start_date: untyped,
      ?end_date: untyped,
      ?next_page_token: untyped,
      ?filter: untyped
    ) -> ::Array[{
      dimensions: ::Array[::String],
      metrics: [{ values: ::Array[::String] }]
    }]
    def self.all: -> ::Array[{
      dimensions: ::Array[::String],
      metrics: [{ values: ::Array[::String] }]
    }]
    def self.reset_all: -> untyped
    def self.update: (untyped) -> untyped

    class JsonKey
      @data: untyped
      def initialize: (untyped) -> untyped
    end
  end
end
