module Ggl
  class BigQuery
    def self.client: -> untyped
    def self.get_page_views: (
      ::Time from_date,
      ?::Time to_date
    ) -> ::Array[{ page_location: ::String, count: ::Integer }]
  end
end
